version: "3.9"

services:
  tor:
    image: alpine:3.20
    container_name: tor
    command: >
      sh -c "apk add --no-cache tor &&
             mkdir -p /etc/tor &&
             echo 'SOCKSPort 0.0.0.0:9050' > /etc/tor/torrc &&
             echo 'ControlPort 0.0.0.0:9051' >> /etc/tor/torrc &&
             echo 'CookieAuthentication 0' >> /etc/tor/torrc &&
             echo 'HashedControlPassword ${TOR_HASHED_PASSWORD}' >> /etc/tor/torrc &&
             tor -f /etc/tor/torrc -f /etc/tor/torrc"
    environment:
      - TOR_HASHED_PASSWORD
    ports:
      - "9050:9050"
      - "9051:9051"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build: .
    container_name: darkweb_api
    depends_on:
      - redis
      - tor
    environment:
      - ENVIRONMENT=prod
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TOR_SOCKS_HOST=tor
      - TOR_SOCKS_PORT=9050
      - TOR_CONTROL_HOST=tor
      - TOR_CONTROL_PORT=9051
      - TOR_CONTROL_PASSWORD=changeme
    ports:
      - "8000:8000"
    restart: unless-stopped

  worker:
    build: .
    container_name: darkweb_worker
    depends_on:
      - redis
      - tor
    environment:
      - ENVIRONMENT=prod
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TOR_SOCKS_HOST=tor
      - TOR_SOCKS_PORT=9050
      - TOR_CONTROL_HOST=tor
      - TOR_CONTROL_PORT=9051
      - TOR_CONTROL_PASSWORD=changeme
    command: ["celery", "-A", "worker.celery", "worker", "--loglevel=info", "-Q", "search,monitor"]
    restart: unless-stopped

