version: "3.8"
services:
  tor:
    image: dperson/torproxy
    container_name: tor
    environment:
      - TRANSPARENT=true
    ports:
      - "9050:9050"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: osint_api
    depends_on:
      - redis
      - tor
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TOR_SOCKS_HOST=tor
      - TOR_SOCKS_PORT=9050
      - TOR_CONTROL_HOST=tor
      - TOR_CONTROL_PORT=9051
      - TOR_CONTROL_PASSWORD=changeme
    ports:
      - "8000:8000"
    volumes:
      - .:/srv/app

  worker:
    build: .
    container_name: osint_worker
    depends_on:
      - redis
      - tor
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TOR_SOCKS_HOST=tor
      - TOR_SOCKS_PORT=9050
      - TOR_CONTROL_HOST=tor
      - TOR_CONTROL_PORT=9051
      - TOR_CONTROL_PASSWORD=changeme
    command: ["celery", "-A", "worker.celery", "worker", "--loglevel=info", "-Q", "search,monitor"]
    volumes:
      - .:/srv/app
